# Configuration for probot/stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14

# Issues with these labels will never be considered stale
exemptLabels:
  - "pinned"
  - "security"
  - "bug"
  - "help wanted"

# Label to apply when marking as stale
staleLabel: "stale"

# Comment to post when marking as stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue
closeComment: false

# Only mark issues as stale, not PRs
only: issues
