# Read the Docs configuration file for mlx-audio
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install mkdocs-material mkdocstrings[python] pymdown-extensions

mkdocs:
  configuration: python/mkdocs.yml
  fail_on_warning: false

# Optionally declare the Python requirements for building docs
python:
  install:
    - method: pip
      path: python
      extra_requirements:
        - dev
